workdir = "workdir"
assets_name = "crypto"
source = None
data_type = None
level = None
tag = f"{assets_name}"
workdir = f"{workdir}/{tag}"
log_path = "process.log"

factors = [
    'atr',
    'bb',
    'beta',
    'cci',
    'cnt',
    'cord',
    'corr',
    'ema',
    'imax',
    'imin',
    'imxd',
    'kdj',
    'klen',
    'klow',
    'kmid',
    'kup',
    'ksft',
    'logvol',
    'ma',
    'macd',
    'max',
    'mfi',
    'min',
    'obv',
    'qtld',
    'qtlu',
    'rank',
    'roc',
    'rsi',
    'rsv',
    'sma',
    'std',
    'sum',
    'vsum',
    'vma',
    'vstd',
    'wvma',
]

processor = dict(
    type = "AggProcessor",
    procs_config = [
        dict(
            type="Processor",
            assets_name=assets_name,
            data_path=f"workdir/{assets_name}_binance_price_1day/price",
            data_type="price",
            assets_path = f"configs/_asset_list_/{assets_name}.json",
            source="binance",
            start_date = "2025-01-01",
            end_date = "2026-01-01",
            level="1day",
            format="%Y-%m-%d",
            max_concurrent = 6,
        ),
        dict(
            type="Processor",
            assets_name=assets_name,
            data_path=f"workdir/{assets_name}_binance_price_1day/price",
            data_type="feature",
            assets_path = f"configs/_asset_list_/{assets_name}.json",
            source="binance",
            start_date = "2025-01-01",
            end_date = "2026-01-01",
            level="1day",
            format="%Y-%m-%d",
            max_concurrent = 6,
        ),
        dict(
            type="Processor",
            assets_name=assets_name,
            data_path=f"workdir/{assets_name}_binance_price_1min/price",
            data_type="price",
            assets_path = f"configs/_asset_list_/{assets_name}.json",
            source="binance",
            start_date = "2026-01-01",
            end_date = "2026-01-12",
            level="1min",
            format="%Y-%m-%d %H:%M:%S",
            max_concurrent = 6,
        ),
        dict(
            type="Processor",
            assets_name=assets_name,
            data_path=f"workdir/{assets_name}_binance_price_1min/price",
            data_type="feature",
            assets_path = f"configs/_asset_list_/{assets_name}.json",
            source="binance",
            start_date = "2026-01-01",
            end_date = "2026-01-12",
            level="1min",
            format="%Y-%m-%d %H:%M:%S",
            max_concurrent = 6,
        )
    ],
    assets_path = f"configs/_asset_list_/{assets_name}.json",
    max_concurrent = 6,
    repo_id = tag,
    repo_type = "dataset",
)